[network]
vgg_config = "config/vgg16.toml"

[dataset]
path = "dataset/cifar-10/"
test_data_num = 300
label_name = ["airplane", "automobile", "bird", "cat", "deer", "dog", "frog", "horse", "ship", "truck"]
image_width = 32
image_height = 32
image_channels = 3
output_class = 10

[train]
batch_size = 10
epoch = 10000
lr = 0.001 #0.001
val_step = 10
use_gpu = true
save_model_path = "saved_model"
save_model_name = "model.dump"